name: Linter Python 3.11

on: [push, pull_request]

jobs:
  linter:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up Python 3.11
        uses: actions/setup-python@v2
        with:
          python-version: 3.11

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r app/requirements.txt

      - name: Run ruff check
        run: |
          pip install ruff
          if ! ruff format --check .; then ruff format .; false; fi
